"""Create the first bounded set of recovery drafts from preserved item folders."""
from __future__ import annotations

from pathlib import Path

from app.core.database import SessionLocal
from app.models.models import MediaRecoveryItemGroup, User
from app.services.media_recovery import MediaRecoveryService

ROOT = Path("/opt/apps/posterpro/repo/backend/storage")
RUN_KEY = "media-recovery-20260720-initial-10"

# Facts are deliberately conservative and directly supported by packaging/photos.
FACTS = {
"SP-20260708-0008": dict(title="Keurig K-Compact Single Serve K-Cup Coffee Maker Black", product_name="Keurig K-Compact single-serve coffee maker", category="Home & Garden > Kitchen, Dining & Bar > Small Kitchen Appliances > Coffee Machines", specifics={"Brand":"Keurig","Type":"Pod Coffee Machine","Color":"Black","Compatible Capsule/Pad System":"K-Cup"}, keywords=["Keurig","K-Compact","K-Cup","single serve","coffee maker"], description="Black K-Compact unit shown with original retail box. Box shows space-saving design, three cup sizes, 36 oz reservoir, and fast brewing.", included="Coffee maker and shown original box; accessories not confirmed", condition="Open box", condition_notes="Original retail box has visible wear, tape residue, and edge damage. Functional testing is not documented.", suggested_price=34.99, quick_sale_price=27.99, price_range="$28–$45", pricing_explanation="Conservative recovery price for an untested open-box small appliance with packaging wear.", shipping="Ground service in a protective outer carton", shipping_weight="9 lb (estimated)", package_dimensions={"length":16,"width":14,"height":12}, confidence=.88, field_confidence={"identity":.95,"condition":.72,"price":.62}, warnings=["Verify brewing function and included manual before publish."], alternatives=[]),
"SP-20260708-0009": dict(title="Discovery RC T-Rex Remote Control Dinosaur Toy with Controller", product_name="Discovery RC T-Rex remote-control dinosaur toy", category="Toys & Hobbies > Radio Control & Control Line > RC Model Vehicles & Kits", specifics={"Brand":"Discovery","Character":"T-Rex","Type":"Remote Control Toy","Theme":"Dinosaurs"}, keywords=["Discovery","RC T-Rex","remote control dinosaur","toy"], description="Discovery branded RC T-Rex set shown in retail packaging with controller pictured on the box.", included="Dinosaur, controller, and only components visible in photos", condition="Open box", condition_notes="Retail box shows shelf wear. Battery operation and completeness are not tested or confirmed.", suggested_price=24.99, quick_sale_price=19.99, price_range="$20–$32", pricing_explanation="Conservative toy price pending confirmation of operation and accessories.", shipping="Ground service; pack controller and dinosaur separately inside carton", shipping_weight="4 lb (estimated)", package_dimensions={"length":18,"width":12,"height":8}, confidence=.86, field_confidence={"identity":.94,"condition":.7,"price":.58}, warnings=["Confirm remote, battery compartment, and movement before publish."], alternatives=[]),
"SP-20260708-0013": dict(title="Multicolor LED Net Lights 4 ft x 6 ft Indoor Outdoor 70 Bulbs", product_name="multicolor LED net lights", category="Home & Garden > Holiday & Seasonal Décor > String Lights", specifics={"Type":"Net Lights","Color":"Multicolor","Indoor/Outdoor":"Indoor & Outdoor","Number of Lights":"70"}, keywords=["LED net lights","multicolor","holiday lights","4x6"], description="Retail box identifies a 4 ft x 6 ft multicolor LED net-light set with 70 bulbs and green wire.", included="One boxed light set; operational status not tested", condition="Open box", condition_notes="Packaging shows wear. Confirm lights illuminate before publication.", suggested_price=16.99, quick_sale_price=12.99, price_range="$13–$22", pricing_explanation="Conservative seasonal-light price pending functional test.", shipping="Ground service in box with additional corner protection", shipping_weight="2 lb (estimated)", package_dimensions={"length":13,"width":10,"height":4}, confidence=.89, field_confidence={"identity":.96,"condition":.7,"price":.58}, warnings=["Test all light sections before publish."], alternatives=[]),
"SP-20260708-0014": dict(title="Gardenline Dual Head Plant Grow Light 10W 40 LED", product_name="Gardenline dual-head plant grow light", category="Home & Garden > Lamps, Lighting & Ceiling Fans > Grow Light Kits", specifics={"Brand":"Gardenline","Type":"Grow Light","Number of LEDs":"40","Power":"10 W"}, keywords=["Gardenline","plant grow light","dual head","40 LED"], description="Gardenline branded dual-head plant grow light in box; package states 10 watts and 40 LEDs.", included="Grow light and components visible in packaging", condition="Open box", condition_notes="Packaging is present. Function and all mounting/accessory pieces need review.", suggested_price=18.99, quick_sale_price=14.99, price_range="$15–$25", pricing_explanation="Conservative price based on photographed 10W consumer grow light.", shipping="Ground service in protected retail box", shipping_weight="2 lb (estimated)", package_dimensions={"length":15,"width":7,"height":4}, confidence=.9, field_confidence={"identity":.97,"condition":.72,"price":.6}, warnings=["Confirm USB/power connection and included clamp before publish."], alternatives=[]),
"SP-20260708-0016": dict(title="Vintage Style Glass Gumball Candy Dispenser White", product_name="glass globe candy or gumball dispenser", category="Collectibles > Advertising > Soda > Vending Machines", specifics={"Type":"Candy Dispenser","Color":"White","Material":"Glass and metal"}, keywords=["gumball machine","candy dispenser","glass globe","vintage style"], description="White-bodied glass-globe dispenser shown from the front. Exact maker, capacity, and working condition are not established by the photos.", included="Dispenser only as pictured", condition="Used", condition_notes="Visible scuffs and grime are present on the base. Mechanism has not been tested.", suggested_price=29.99, quick_sale_price=22.99, price_range="$23–$40", pricing_explanation="Conservative used decorative dispenser price with unknown maker and untested mechanism.", shipping="Ground service with globe immobilized and double-boxed", shipping_weight="7 lb (estimated)", package_dimensions={"length":12,"width":12,"height":18}, confidence=.65, field_confidence={"identity":.72,"condition":.72,"price":.48}, warnings=["Verify globe condition, coin mechanism, and exact capacity before publish."], alternatives=["Decorative candy dispenser"]),
"SP-20260708-0020": dict(title="Bed Head Tourmaline Ceramic Deep Waver Hair Styler", product_name="Bed Head tourmaline ceramic deep waver", category="Health & Beauty > Hair Care & Styling > Hair Styling Devices", specifics={"Brand":"Bed Head","Type":"Hair Waver","Material":"Tourmaline Ceramic"}, keywords=["Bed Head","deep waver","hair styler","tourmaline ceramic"], description="Bed Head packaging describes tourmaline ceramic technology, a deep waver barrel, multiple heat settings, and instant recovery.", included="Styling tool and components visible in photos", condition="Open box", condition_notes="Retail packaging has visible damage. Power-on and heat operation are not documented.", suggested_price=22.99, quick_sale_price=17.99, price_range="$18–$32", pricing_explanation="Conservative open-box hair-tool price pending electrical test.", shipping="Ground service with tool secured in retail box", shipping_weight="3 lb (estimated)", package_dimensions={"length":16,"width":7,"height":4}, confidence=.88, field_confidence={"identity":.93,"condition":.7,"price":.58}, warnings=["Test heating and inspect cord before publish."], alternatives=[]),
"SP-20260708-0024": dict(title="Spectra Premium SP4066M Fuel Delivery Assembly", product_name="Spectra Premium fuel delivery assembly", category="eBay Motors > Parts & Accessories > Car & Truck Parts & Accessories > Fuel Pumps & Sending Units", specifics={"Brand":"Spectra Premium","Manufacturer Part Number":"SP4066M","Type":"Fuel Delivery Assembly"}, keywords=["Spectra Premium","SP4066M","fuel delivery assembly","fuel pump"], description="Box label identifies Spectra Premium Fuel Delivery Assembly SP4066M. Vehicle fitment must be confirmed by the buyer and operator before publication.", included="Boxed fuel delivery assembly; contents not inventoried", condition="Open box", condition_notes="Box has significant wear. Do not claim compatibility until part number fitment is verified.", suggested_price=54.99, quick_sale_price=42.99, price_range="$43–$70", pricing_explanation="Part-number-based conservative automotive price pending fitment and contents review.", shipping="Ground service in reinforced outer carton", shipping_weight="5 lb (estimated)", package_dimensions={"length":16,"width":12,"height":8}, confidence=.9, field_confidence={"identity":.98,"condition":.65,"price":.6}, warnings=["Verify contents, damage, and vehicle fitment using SP4066M before publish."], alternatives=[]),
"SP-20260708-0027": dict(title="RYOBI LINK Modular Wall Storage Accessory Black Green", product_name="RYOBI LINK modular wall-storage accessory", category="Home & Garden > Tools & Workshop Equipment > Tool Storage & Organization", specifics={"Brand":"RYOBI","Product Line":"LINK","Color":"Black and Green","Type":"Tool Storage Accessory"}, keywords=["RYOBI LINK","wall storage","tool organizer","modular"], description="RYOBI LINK-branded black and green modular storage component shown in the preserved item photos.", included="Storage component(s) visible in photos only", condition="Used", condition_notes="Used condition with visible dirt/scuffs. Exact kit configuration requires photo review.", suggested_price=19.99, quick_sale_price=14.99, price_range="$15–$30", pricing_explanation="Conservative used tool-storage accessory price with configuration review required.", shipping="Ground service with edges protected", shipping_weight="4 lb (estimated)", package_dimensions={"length":24,"width":8,"height":5}, confidence=.75, field_confidence={"identity":.82,"condition":.72,"price":.5}, warnings=["Confirm exact LINK components and mounting hardware before publish."], alternatives=["RYOBI LINK wall rail accessory"]),
"SP-20260708-0028": dict(title="RYOBI Electric Pressure Washer with Hose Green", product_name="RYOBI electric pressure washer", category="Home & Garden > Yard, Garden & Outdoor Living > Outdoor Power Equipment > Pressure Washers", specifics={"Brand":"RYOBI","Power Source":"Corded Electric","Type":"Pressure Washer","Color":"Green"}, keywords=["RYOBI","electric pressure washer","power washer","hose"], description="Green RYOBI corded pressure washer shown with hose in preserved item photos. Exact PSI/GPM and accessories are not confirmed.", included="Pressure washer and hose visible in photos", condition="Used", condition_notes="Used exterior condition. Pump, spray function, and accessories are untested.", suggested_price=49.99, quick_sale_price=37.99, price_range="$38–$70", pricing_explanation="Conservative used equipment price pending functional test and model verification.", shipping="Local pickup preferred; otherwise ground shipment after measured packing", shipping_weight="22 lb (estimated)", package_dimensions={"length":24,"width":16,"height":14}, confidence=.73, field_confidence={"identity":.8,"condition":.7,"price":.48}, warnings=["Verify model, PSI/GPM, spray wand, and water pressure operation before publish."], alternatives=["RYOBI corded outdoor cleaning tool"]),
"SP-20260708-0031": dict(title="RYOBI ONE+ 18V Cordless Tool P5231", product_name="RYOBI ONE+ 18V cordless tool", category="Home & Garden > Tools & Workshop Equipment > Power Tools", specifics={"Brand":"RYOBI","Product Line":"ONE+","Voltage":"18 V","Model":"P5231"}, keywords=["RYOBI","ONE+","P5231","18V cordless tool"], description="RYOBI tool label in preserved photos identifies model P5231 and 18V battery platform. Exact tool type and included battery/charger must be verified before publication.", included="Tool shown in photos only; battery and charger not confirmed", condition="Used", condition_notes="Used condition with dirt/scuffs visible. Operation has not been documented.", suggested_price=34.99, quick_sale_price=25.99, price_range="$26–$50", pricing_explanation="Conservative bare-tool price based on visible 18V model identification.", shipping="Ground service with battery removed if present", shipping_weight="7 lb (estimated)", package_dimensions={"length":18,"width":10,"height":8}, confidence=.77, field_confidence={"identity":.86,"condition":.7,"price":.5}, warnings=["Verify exact tool type, battery inclusion, and operation before publish."], alternatives=[]),
}


def generic_review_facts(item_id: str) -> dict:
    """A complete but intentionally non-specific draft for a bounded photo set.

    This is preferable to inventing a brand/model when the preserved images have
    not yielded a defensible identity.  It is explicitly marked for identity
    review and never becomes publish-ready automatically.
    """
    return {
        "title": "Recovered photographed inventory item – identity review",
        "product_name": "photographed inventory item in a sealed recovery media group",
        "category": "General resale > Identity review required",
        "specifics": {"Brand": "Review photo evidence", "Type": "Identity review required", "Recovery SKU": item_id},
        "keywords": ["recovered inventory", "photo review", "identity review"],
        "description": "A bounded set of preserved original photographs is attached. No exact brand, model, compatibility, or completeness claim is made until an operator reviews the evidence.",
        "included": "Only components visible in the attached photographs",
        "condition": "Used",
        "condition_notes": "Condition, operation, measurements, and completeness require photo review before publishing.",
        "suggested_price": 19.99,
        "quick_sale_price": 14.99,
        "price_range": "$15–$30",
        "pricing_explanation": "Conservative temporary recovery price; replace after identity and condition review.",
        "shipping": "Do not publish until measured and packed; ground service is a provisional recommendation.",
        "shipping_weight": "3 lb (estimated)",
        "package_dimensions": {"length": 12, "width": 10, "height": 8},
        "confidence": 0.42,
        "field_confidence": {"grouping": 0.96, "identity": 0.15, "condition": 0.35, "price": 0.2},
        "warnings": ["Identity review required before publish.", "Verify condition, completeness, measurements, and shipping details."],
        "alternatives": [],
    }

def main() -> None:
    with SessionLocal() as db:
        user = db.query(User).order_by(User.id).first()
        if not user:
            raise RuntimeError("A live PosterPro user is required before recovery drafts can be created.")
        service = MediaRecoveryService()
        run = service.manifest(db, user=user, roots=[ROOT / "intake-google-photos", ROOT / "intake-items"], run_key=RUN_KEY)
        service.group_item_directories(db, run=run)
        created = []
        groups = db.query(MediaRecoveryItemGroup).filter_by(run_id=run.id, grouping_status="confirmed").order_by(MediaRecoveryItemGroup.recovery_item_id).all()
        for group in groups:
            facts = FACTS.get(group.recovery_item_id) or generic_review_facts(group.recovery_item_id)
            created.append(service.create_draft(db, user=user, group=group, facts=facts))
        service.finalize(db, run=run, draft_count=len(created))
        print({"run_id": run.id, "draft_ids": [listing.id for listing in created], "draft_count": len(created)})

if __name__ == "__main__":
    main()
