[Unit]
After=posterpro-bridge-xvfb.service posterpro-bridge-fluxbox.service
Requires=posterpro-bridge-xvfb.service posterpro-bridge-fluxbox.service

[Service]
Environment=DISPLAY=:99
Environment=LIBGL_ALWAYS_SOFTWARE=1
