ALTER TABLE listings
    ADD COLUMN IF NOT EXISTS start_price DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS buy_it_now_price DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS min_acceptable_offer DOUBLE PRECISION;
