ALTER TABLE listings ADD COLUMN IF NOT EXISTS listing_price DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS purchase_cost DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS fees_estimated DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS fees_actual DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS shipping_cost DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS sale_price DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS profit DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS roi_percentage DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS sold_at TIMESTAMP;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS photo_quality_score DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS condition VARCHAR(64);

CREATE TABLE IF NOT EXISTS daily_stats (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    stat_date DATE NOT NULL,
    total_revenue DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    roi_percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
    sell_through_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_days_to_sell DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS category_stats (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    category VARCHAR(255) NOT NULL,
    total_listed INTEGER NOT NULL DEFAULT 0,
    total_sold INTEGER NOT NULL DEFAULT 0,
    avg_days_to_sell DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_sale_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    sell_through_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS listing_predictions (
    id SERIAL PRIMARY KEY,
    listing_id INTEGER NOT NULL UNIQUE REFERENCES listings(id),
    probability_sale_7d DOUBLE PRECISION NOT NULL DEFAULT 0,
    probability_sale_30d DOUBLE PRECISION NOT NULL DEFAULT 0,
    model_version VARCHAR(64) NOT NULL DEFAULT 'heuristic-v1',
    features JSON,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS listing_ab_test_variants (
    id SERIAL PRIMARY KEY,
    listing_id INTEGER NOT NULL REFERENCES listings(id),
    variant_label VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    impressions INTEGER NOT NULL DEFAULT 0,
    clicks INTEGER NOT NULL DEFAULT 0,
    watch_count INTEGER NOT NULL DEFAULT 0,
    conversions INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
