import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import AppShell from "../../components/layout/AppShell";
import Button from "../../components/ui/button";
import PageHeader from "../../components/ui/page-header";
import { fetchProcessingBlockers, updateListing } from "../../lib/api";

export default function BlockerQueuePage() {
  const router = useRouter();
  const reason = typeof router.query.reason === "string" ? router.query.reason : "";
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [titles, setTitles] = useState({}); const [saving, setSaving] = useState({});
  useEffect(() => { if (!router.isReady || !reason) return; setLoading(true); fetchProcessingBlockers(reason, 250).then(setData).finally(() => setLoading(false)); }, [router.isReady, reason]);
  const identityBlocker = /title|identity|generic|unknown|caption/i.test(reason);
  const imageBlocker = /image|photo|primary|gallery/i.test(reason);
  return <AppShell active="/jobs" title="Blocker queue"><PageHeader title={reason || "Blocker queue"} description="Affected listings, evidence, and inline repair options." actions={<Button variant="outline" onClick={() => router.push("/jobs")}>Back to Jobs</Button>} />
    <div className="mb-4 flex flex-wrap items-center justify-between rounded-xl border border-[var(--pp-border)] bg-[var(--pp-surface)] p-4"><p className="text-sm font-semibold">{data?.count ?? "—"} affected listings</p><Button onClick={() => router.push(`/listings?queue=needs_attention&blocker=${encodeURIComponent(reason)}`)}>Open filtered Listings</Button></div>
    {loading ? <p className="text-sm text-[var(--pp-muted)]">Loading affected listings…</p> : <div className="space-y-3">{(data?.items || []).map((item) => <article key={item.id} className="pp-card grid gap-3 p-4 md:grid-cols-[56px_1fr_auto] md:items-center"><div style={{ width: 48, height: 48, minWidth: 48, minHeight: 48 }} className="overflow-hidden rounded-lg bg-slate-100">{item.image_urls?.[0] ? <img src={item.image_urls[0]} alt="" style={{ width: 48, height: 48, maxWidth: 48, maxHeight: 48, objectFit: "cover", display: "block" }} /> : null}</div><div className="min-w-0"><a className="font-semibold text-[var(--pp-accent)] hover:underline" href={`/listings/${item.id}`}>{item.title || `Listing #${item.id}`}</a><p className="mt-1 text-xs text-[var(--pp-muted)]">#{item.id} · {item.source_type || "unknown"} · {item.processing_stage || item.processing_state}</p><p className="mt-1 text-sm text-slate-600">{item.next_action}</p>{identityBlocker ? <label className="mt-2 block text-xs font-semibold uppercase tracking-wide text-slate-500">Replacement title / identity<input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" value={titles[item.id] ?? item.title ?? ""} onChange={(event) => setTitles((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="Enter a specific sellable identity" /></label> : <p className="mt-2 text-xs font-semibold text-amber-700">Required correction: {imageBlocker ? "upload/approve the correct item image and primary image" : "resolve the blocker evidence shown above"}</p>}</div><div className="flex flex-wrap gap-2">{identityBlocker ? <Button size="sm" variant="outline" disabled={saving[item.id]} onClick={async () => { setSaving((current) => ({ ...current, [item.id]: true })); try { await updateListing(item.id, { title: titles[item.id] ?? item.title }); setData((current) => ({ ...current, items: current.items.map((row) => row.id === item.id ? { ...row, title: titles[item.id] ?? item.title } : row) })); } finally { setSaving((current) => ({ ...current, [item.id]: false })); } }}>{saving[item.id] ? "Saving…" : "Save field"}</Button> : null}<Button size="sm" onClick={() => router.push(`/listings/${item.id}?mode=repair`)}>Fix automatically</Button></div></article>)}{!data?.items?.length ? <p className="text-sm text-[var(--pp-muted)]">No listings currently match this blocker.</p> : null}</div>}
  </AppShell>;
}
