export const ADMIN_THEMES = [
  {
    id: 'posterpro-classic',
    name: 'PosterPro Classic',
    description: 'Clean bright SaaS dashboard with blue operator accents.',
    category: 'SaaS',
    mode: 'light',
    className: 'theme-posterpro-classic',
    accentLabel: 'Default',
    preview: { background: '#f7f9fc', surface: '#ffffff', primary: '#2563eb', accent: '#0ea5e9', text: '#101828' },
  },
  {
    id: 'midnight-operator',
    name: 'Midnight Operator',
    description: 'Dark navy operations layout with crisp indigo focus.',
    category: 'Operations',
    mode: 'dark',
    className: 'theme-midnight-operator',
    preview: { background: '#0b1220', surface: '#111a2d', primary: '#4f7cff', accent: '#7dd3fc', text: '#e2e8f0' },
  },
  {
    id: 'graphite-pro',
    name: 'Graphite Pro',
    description: 'Neutral grayscale theme inspired by modern dev tools.',
    category: 'Minimal',
    mode: 'light',
    className: 'theme-graphite-pro',
    preview: { background: '#f4f4f5', surface: '#ffffff', primary: '#27272a', accent: '#52525b', text: '#09090b' },
  },
  {
    id: 'emerald-market',
    name: 'Emerald Market',
    description: 'Commerce-forward green and teal palette for inventory teams.',
    category: 'Commerce',
    mode: 'light',
    className: 'theme-emerald-market',
    preview: { background: '#f3faf7', surface: '#ffffff', primary: '#0f766e', accent: '#10b981', text: '#0f172a' },
  },
  {
    id: 'sunset-ledger',
    name: 'Sunset Ledger',
    description: 'Warm amber highlights tuned for sales and bookkeeping.',
    category: 'Finance',
    mode: 'light',
    className: 'theme-sunset-ledger',
    preview: { background: '#fff8f1', surface: '#ffffff', primary: '#c2410c', accent: '#f59e0b', text: '#111827' },
  },
  {
    id: 'royal-grape',
    name: 'Royal Grape',
    description: 'Polished violet SaaS palette with high readability.',
    category: 'Creative',
    mode: 'light',
    className: 'theme-royal-grape',
    preview: { background: '#f8f7ff', surface: '#ffffff', primary: '#6d28d9', accent: '#a855f7', text: '#1f1147' },
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'Charcoal foundation with controlled cyan and magenta accents.',
    category: 'Dark',
    mode: 'dark',
    className: 'theme-cyberpunk-neon',
    preview: { background: '#0a0b12', surface: '#11131d', primary: '#22d3ee', accent: '#f472b6', text: '#f3f4f6' },
  },
  {
    id: 'vintage-paper',
    name: 'Vintage Paper',
    description: 'Warm catalog feel with parchment tones and ink contrast.',
    category: 'Boutique',
    mode: 'light',
    className: 'theme-vintage-paper',
    preview: { background: '#f9f4e8', surface: '#fffaf0', primary: '#7c3f00', accent: '#b45309', text: '#3f2a16' },
  },
  {
    id: 'terminal-noir',
    name: 'Terminal Noir',
    description: 'Operator terminal-inspired dark UI with green diagnostics.',
    category: 'Dark',
    mode: 'dark',
    className: 'theme-terminal-noir',
    preview: { background: '#05070a', surface: '#0d1117', primary: '#22c55e', accent: '#16a34a', text: '#d1fae5' },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Accessibility-first palette with strong borders and focus cues.',
    category: 'Accessibility',
    mode: 'high-contrast',
    className: 'theme-high-contrast',
    accentLabel: 'A11y',
    preview: { background: '#ffffff', surface: '#ffffff', primary: '#000000', accent: '#1d4ed8', text: '#000000' },
  },
];

export const DEFAULT_ADMIN_THEME_ID = 'posterpro-classic';

export function getAdminThemeById(themeId) {
  return ADMIN_THEMES.find((theme) => theme.id === themeId) || ADMIN_THEMES[0];
}
